#!/usr/bin/env bash
set -euo pipefail

BRANCH_NAME="$1"
BRIEF_FILE=".delta/BRIEF.md"

if [[ ! -f "$BRIEF_FILE" ]]; then
  echo "Error: .delta/BRIEF.md not found" >&2
  exit 1
fi

TITLE=$(grep "^# Feature Brief:" "$BRIEF_FILE" | head -1 | sed 's/^# Feature Brief: *//')
TODAY=$(date +%Y-%m-%d)

PR_BODY=$(cat <<BODY
## Delta Daily Feature — $TODAY

$(cat "$BRIEF_FILE")

---
*This PR was automatically generated by Delta. Review it, check the Vercel preview, then merge or close.*
BODY
)

# Skip if a PR with the same title is already open
EXISTING=$(gh pr list --state open --search "\"$TITLE\" in:title" --json number,title \
  --jq '.[0].number // empty')
if [[ -n "$EXISTING" ]]; then
  echo "Skipping — PR #$EXISTING already open with title: $TITLE"
  exit 0
fi

# Ensure labels exist (create if missing)
gh label create "delta" --color "0075ca" --description "Generated by Delta" 2>/dev/null || true
gh label create "awaiting-review" --color "e4e669" --description "Awaiting human review" 2>/dev/null || true

gh pr create \
  --title "$TITLE" \
  --body "$PR_BODY" \
  --label "delta" \
  --label "awaiting-review" \
  --base main \
  --head "$BRANCH_NAME"
