#!/usr/bin/env bash
set -euo pipefail

FEATURE_NAME="${1:-unknown}"
TODAY=$(date +%Y-%m-%d)
BLOCKED_FILE=".delta/BLOCKED.md"

BODY=$(cat <<BODY
## Delta Blocked — $TODAY

The developer agent could not complete today's feature: **$FEATURE_NAME**

$(cat "$BLOCKED_FILE" 2>/dev/null || echo "No BLOCKED.md written by agent.")

---

### How to unblock

1. Review \`.delta/BRIEF.md\` — is the feature too complex or ambiguous?
2. Either simplify the brief manually, or remove the feature from \`.delta/BACKLOG.md\`
3. Delete \`.delta/BLOCKED.md\` before the next cycle
4. The next cycle will pick the next Ready item from the backlog

*This issue was automatically generated by Delta.*
BODY
)

gh label create "delta-blocked" --color "d93f0b" --description "Delta cycle blocked" 2>/dev/null || true

gh issue create \
  --title "Delta blocked: $FEATURE_NAME ($TODAY)" \
  --body "$BODY" \
  --label "delta-blocked"
